# ===========================================
# PROFILE: HOMOLOGAÇÃO
# ===========================================
spring:
  application:
    name: agrogame-api-hml
  datasource:
    # A URL e o Driver são injetados automaticamente pelo starter do Spring Cloud GCP
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
    open-in-view: false

  # ===========================================
  # FILE UPLOAD CONFIGURATION
  # ===========================================
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

  cloud:
    gcp:
      project-id: agrogame
      sql:
        database-name: ${DB_NAME}
        instance-connection-name: agrogame:us-central1:agrogame-postgres-hml
      pubsub:
        enable: true

server:
  port: ${PORT:8080}
  compression:
    enabled: true
    tomcat:
      remoteip:
        remote-ip-header: X-Forwarded-For
        protocol-header: X-Forwarded-Proto
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true

logging:
  level:
    root: INFO
    br.com.agrogame.agrogame: DEBUG
    org.hibernate.SQL: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

app:
  swagger:
    server-url: https://hml-api.agribit.com.br
    server-description: HMl / STG
  pagination:
    default-page-size: 20
    max-page-size: 100
  points:
    max-transaction-per-day: 50

# === PROPRIEDADES DE INFRAESTRUTURA DA APLICAÇÃO ===
agrogame:
  pubsub:
    email-topic: dev-notifications-email
  storage:
    bucket-name: agrogame-uploads-hml
